PurpuraWeb/Controllers/CompanyEmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Purpura.Abstractions.ServiceInterfaces;
using Purpura.Models.ViewModels;
using System.Threading.Tasks;

namespace PurpuraWeb.Controllers
{
    [Authorize(Roles = "Manager")]
    [Route("/[controller]/")]
    public class CompanyEmployeeController : Controller
    {
        private readonly ICompanyEmployeeService _companyEmployeeService;

        public CompanyEmployeeController(ICompanyEmployeeService companyEmployeeService)
        {
            _companyEmployeeService = companyEmployeeService;
        }

        [HttpGet]
        public IActionResult Create(string companyReference)
        {
            var viewModel = new CompanyEmployeeViewModel { CompanyExternalReference = companyReference };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CompanyEmployeeViewModel viewModel)
        {
            var companyEmployee = await _companyEmployeeService.GetAsync(ce => ce.Email == viewModel.Email);

            if(companyEmployee != null)
            {
                ModelState.AddModelError("Email", "A Company Employee has already been created with this email.");
            }

            if (ModelState.IsValid)
            {
                var result = await _companyEmployeeService.CreateAsync(viewModel);

                if (result.IsSuccess)
                {
                    return RedirectToAction("Details", "Company", new { companyReference = viewModel.CompanyExternalReference });
                }

                viewModel.Result = result;
            }

            return View(viewModel);
        }

        [HttpGet("Edit/{companyEmployeeRef}")]
        public async Task<IActionResult> Edit(string companyEmployeeRef)
        {
            var employee = await _companyEmployeeService.GetByExternalReferenceAsync(companyEmployeeRef);

            return View(employee);
        }

        [HttpPost("Edit/{companyEmployeeRef}")]
        public async Task<IActionResult> Edit(CompanyEmployeeViewModel viewModel)
        {
            var companyEmployee = await _companyEmployeeService.GetAsync(ce => ce.Email == viewModel.Email);

            if (companyEmployee != null && (companyEmployee.Email != viewModel.Email))
            {
                ModelState.AddModelError("Email", "A Company Employee has already been created with this email.");
            }

            if (ModelState.IsValid)
            {
                var result = await _companyEmployeeService.EditAsync(viewModel);

                if (result.IsSuccess)
                {
                    return RedirectToAction("Details", "Company", new { companyReference = viewModel.CompanyExternalReference });
                }

                viewModel.Result = result;
            }

            return View(viewModel);
        }

        [HttpGet("Details/{companyEmployeeRef}")]
        public async Task<IActionResult> Details(string companyEmployeeRef)
        {
            var employee = await _companyEmployeeService.GetByExternalReferenceAsync(companyEmployeeRef);

            return View(employee);
        }
    }
}

PurpuraWeb/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Purpura.Abstractions.ServiceInterfaces;
using Purpura.Models.ViewModels;
using Purpura.Utility.Helpers;

namespace PurpuraWeb.Controllers
{
    [Route("[controller]")]
    public class UserManagementController : Controller
    {
        private readonly IUserManagementService _userManagementService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public UserManagementController(IUserManagementService userManagementService, 
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _userManagementService = userManagementService;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        [Route("Details/{userId}")]
        public async Task<IActionResult> Details(string userId)
        {
            var userViewModel = await _userManagementService.GetUser(u => u.Id == userId);

            if (userViewModel == null)
                return NotFound();

            return View(userViewModel);
        }

        [HttpGet]
        [Route("Edit/{userId}")]
        public async Task<IActionResult> Edit(string userId)
        {
            var userViewModel = await _userManagementService.GetUser(u => u.Id == userId);

            if (userViewModel == null)
                return NotFound();

            userViewModel.GenderList = EnumHelpers.GenerateGenderSelectList();
            userViewModel.TitleList = EnumHelpers.GenerateTitleSelectList();

            return View(userViewModel);
        }

        [HttpPost]
        [Route("Edit/{userId}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUserViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Address = AddressHelpers.ConstructAddressString(new string[4] { viewModel.AddressLine1, viewModel.AddressLine2, viewModel.AddressLine3, viewModel.Postcode });

                var result = await _userManagementService.UpdateUser(viewModel);

                if (result.IsSuccess)
                {
                    var nameString = viewModel.MiddleName != null ? $"{viewModel.FirstName} {viewModel.MiddleName} {viewModel.LastName}" : $"{viewModel.FirstName} {viewModel.LastName}";
                    var nameClaim = User.Claims.FirstOrDefault(c => c.Type == "Name");

                    if(nameClaim != null && (nameString.ToLower() != nameClaim.Value.ToLower()))
                    {
                        var user = await _userManager.GetUserAsync(User);
                        await _signInManager.RefreshSignInAsync(user);
                    }

                    return RedirectToAction($"Details", new { userId = viewModel.Id });
                }

                viewModel.Result = result;
            }

            viewModel.GenderList = EnumHelpers.GenerateGenderSelectList();
            viewModel.TitleList = EnumHelpers.GenerateTitleSelectList();

            return View(viewModel);
        }

        [HttpPost("CheckUserEmailExists")]
        public async Task<IActionResult> CheckUserEmailExists(string input)
        {
            if (!string.IsNullOrEmpty(input))
            {
                var normalisedEmail = _userManager.NormalizeEmail(input);
                var user = await _userManager.FindByEmailAsync(normalisedEmail);
                return Json(user != null);
            }

            return Json(false);
        }
    }
}

PurpuraWeb/Views/CompanyEmployee/Create.cshtml
@model CompanyEmployeeViewModel;

<h1 class="form-title">Add Company Employee</h1>
<p style="width: 60%;">Create a Company Employee. If a user is already on the system that has the supplied email then on creation the Company Employee will be matched to that user. If there is no match then when the user registers they will be assigned to the Company Employee on registration.</p>

<form asp-action="Create" asp-controller="CompanyEmployee" class="post-forms">

    <input type="hidden" asp-for="CompanyExternalReference" />
    <input type="hidden" asp-for="EmailExists" />

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="FirstName" placeholder="" />
        <label asp-for="FirstName">First Name</label>
        <span asp-validation-for="FirstName"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="MiddleName" placeholder="" />
        <label asp-for="MiddleName">Middle Name(s)</label>
        <span asp-validation-for="MiddleName"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="LastName" placeholder="" />
        <label asp-for="LastName">Last Name</label>
        <span asp-validation-for="LastName"></span>
    </div>

    <div id="existing-email-validation"></div>
    <div class="form-floating mb-3">
        <input class="form-control" type="email" asp-for="Email" placeholder="" />
        <label asp-for="Email">Email</label>
        <span asp-validation-for="Email"></span>
    </div>
    
    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="JobTitle" placeholder="" />
        <label asp-for="JobTitle">Job Title</label>
        <span asp-validation-for="JobTitle"></span>
    </div>

    @if (Model.Result != null && Model.Result.Error != null)
    {
        <div class="field-validation-error">@Model.Result.Error</div>
    }

    <div class="form-button-container">
        <a asp-action="Details" asp-controller="Company" asp-route-companyReference="@Model.CompanyExternalReference" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <button type="submit" class="btn btn-success"><i class="bi bi-check2 button-icons"></i>Submit</button>
    </div>
</form>

@section Scripts {
    <script>
        initialiseEmailCheckAjax('@Url.Action("CheckUserEmailExists", "UserManagement")');
    </script>
}

PurpuraWeb/Views/CompanyEmployee/Details.cshtml
@model CompanyEmployeeViewModel;

<h1 class="form-title">Employee Details</h1>

<div class="details-container">
    <dl>
        <dt>First Name</dt>
        <dd>@Model.FirstName</dd>

        <dt>Middle Name(s)</dt>
        <dd>@Model.MiddleName</dd>

        <dt>Last Name</dt>
        <dd>@Model.LastName</dd>

        <dt>Job Title</dt>
        <dd>@Model.JobTitle</dd>
    </dl>
    <div>
        <a asp-action="Details" asp-controller="Company" asp-route-companyReference="@Model.CompanyExternalReference" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <a asp-action="Edit" asp-controller="CompanyEmployee" asp-route-companyEmployeeRef="@Model.ExternalReference" class="btn btn-purpura"><i class="bi bi-pencil-square button-icons"></i>Edit</a>
    </div>
</div>

PurpuraWeb/Views/CompanyEmployee/Edit.cshtml
@model CompanyEmployeeViewModel;

<h1 class="form-title">Edit Company Employee</h1>

<form asp-action="Create" asp-controller="CompanyEmployee" class="post-forms">

    <input type="hidden" asp-for="CompanyExternalReference" />
    <input type="hidden" asp-for="EmailExists" />
    <input type="hidden" asp-for="ExternalReference" />

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="FirstName" placeholder="" />
        <label asp-for="FirstName">First Name</label>
        <span asp-validation-for="FirstName"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="MiddleName" placeholder="" />
        <label asp-for="MiddleName">Middle Name(s)</label>
        <span asp-validation-for="MiddleName"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="LastName" placeholder="" />
        <label asp-for="LastName">Last Name</label>
        <span asp-validation-for="LastName"></span>
    </div>

    <div id="existing-email-validation"></div>
    <div class="form-floating mb-3">
        <input class="form-control" type="email" asp-for="Email" placeholder="" />
        <label asp-for="Email">Email</label>
        <span asp-validation-for="Email"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="JobTitle" placeholder="" />
        <label asp-for="JobTitle">Job Title</label>
        <span asp-validation-for="JobTitle"></span>
    </div>

    @if (Model.Result != null && Model.Result.Error != null)
    {
        <div class="field-validation-error">@Model.Result.Error</div>
    }

    <div class="form-button-container">
        <a asp-action="Details" asp-controller="Company" asp-route-companyReference="@Model.CompanyExternalReference" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <button asp-action="Edit" asp-controller="CompanyEmployee" type="submit" class="btn btn-success"><i class="bi bi-check2 button-icons"></i>Submit</button>
    </div>
</form>

@section Scripts {
    <script>
        initialiseEmailCheckAjax('@Url.Action("CheckUserEmailExists", "UserManagement")');
    </script>
}