PurpuraWeb/Controllers/GoalController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Purpura.Abstractions.ServiceInterfaces;
using Purpura.Models.ViewModels;

namespace PurpuraWeb.Controllers
{
    public class GoalController : Controller
    {
        private readonly IGoalService _goalService;
        private readonly UserManager<IdentityUser> _userManager;

        public GoalController(IGoalService goalService, UserManager<IdentityUser> userManager)
        {
            _goalService = goalService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userGoals = await _goalService.GetAllGoalsByUserIdAsync(_userManager.GetUserId(User));

            var viewModel = new GoalIndexViewModel()
            {
                Goals = userGoals
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new GoalViewModel()
            {
                UserId = _userManager.GetUserId(User)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GoalViewModel viewModel)
        {
            if(viewModel.IsDateRequired && (viewModel.DueDate == null || viewModel.DueDate == DateTime.MinValue))
            {
                ModelState.AddModelError("DueDate", "Please provide a due date.");
            }

            if (ModelState.IsValid)
            {
                var result = await _goalService.CreateAsync(viewModel);

                if (result.IsSuccess)
                    return RedirectToAction("Index");
                else
                    viewModel.OperationFailure = true;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string reference)
        {
            var goalViewModel = await _goalService.GetByExternalReferenceAsync(reference);

            if (goalViewModel == null)
            {
                return RedirectToAction("Index");
            }

            return View(goalViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string reference)
        {
            var goalViewModel = await _goalService.GetByExternalReferenceAsync(reference);

            if (goalViewModel.DueDate != null)
            {
                goalViewModel.IsDateRequired = true;
            }

            return View(goalViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GoalViewModel goalViewModel)
        {
            if (goalViewModel.IsDateRequired && (goalViewModel.DueDate == null || goalViewModel.DueDate == DateTime.MinValue))
            {
                ModelState.AddModelError("DueDate", "Please provide a due date.");
            }
            else
            {
                goalViewModel.DueDate = null;
            }

            if (ModelState.IsValid)
            {
                var result = await _goalService.EditAsync(goalViewModel);

                if (result.IsSuccess)
                {
                    return RedirectToAction("Details", new { reference = goalViewModel.ExternalReference });
                }
                else
                {
                    goalViewModel.Result = result;
                }
            }

            return View(goalViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string reference)
        {
            var goalViewModel = await _goalService.GetByExternalReferenceAsync(reference);

            if(goalViewModel == null)
            {
                return RedirectToAction("Index");
            }

            return View(goalViewModel);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(GoalViewModel viewModel)
        {
            var result = await _goalService.DeleteAsync(viewModel);

            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                viewModel.Result = result;
            }

            return View(viewModel);
        }
    }
}

PurpuraWeb/Views/Goal/Create.cshtml
@model GoalViewModel;

<h1 class="form-title">Create Goal</h1>

<form asp-action="Create" asp-controller="Goal" class="post-forms">

    <div class="form-check form-switch due-date-switch-container">
        <input class="form-check-input form-control" type="checkbox" role="switch" id="due-date-switch" asp-for="IsDateRequired">
        <label class="form-check-label" for="switchCheckDefault">Due Date Required</label>
    </div>

    <div class="form-floating mb-3 due-date-field-container" style="display: none;">
        <input class="form-control" type="date" asp-for="DueDate" placeholder="1" />
        <label asp-for="DueDate">Due Date</label>
        <span asp-validation-for="DueDate"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="Name" placeholder="My Goal" />
        <label asp-for="Name">Goal Name</label>
        <span asp-validation-for="Name" class="mb-3"></span>
    </div>

    <div class="form-floating mb-3">
        <textarea class="form-control" asp-for="Description" placeholder=""></textarea>
        <label asp-for="Description">Description</label>
        <span asp-validation-for="Description"></span>
    </div>

    <input type="hidden" asp-for="UserId" />

    <div class="form-button-container">
        <a asp-action="Index" asp-controller="Goal" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <button type="submit" class="btn btn-success"><i class="bi bi-check2 button-icons"></i>Submit</button>
    </div>
</form>

@section Scripts{
    <script>
        if(@Model.OperationFailure.ToString().ToLower()){
            toastr.error("Create failed.")
        }

        goalCreateEditForms();
    </script>
}

PurpuraWeb/Views/Goal/Delete.cshtml
@model GoalViewModel;

<h1 class="form-title">Delete Goal</h1>
<h2 style="color: red;">Once this has been deleted it can not be undone!</h2>

<form asp-action="Delete" asp-controller="Goal" class="post-forms">

    <div class="form-floating mb-3">
        <input class="form-control" type="date" asp-for="DueDate" readonly placeholder="1" />
        <label asp-for="DueDate">Due Date</label>
        <span asp-validation-for="DueDate"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="Name" readonly placeholder="My Goal" />
        <label asp-for="Name">Goal Name</label>
        <span asp-validation-for="Name" class="mb-3"></span>
    </div>

    <div class="form-floating mb-3">
        <textarea class="form-control" asp-for="Description" readonly placeholder=""></textarea>
        <label asp-for="Description">Description</label>
        <span asp-validation-for="Description"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" asp-for="PercentageComplete" readonly placeholder="">
        <label asp-for="PercentageComplete">Percentage Complete</label>
        <span asp-validation-for="PercentageComplete"></span>
    </div>

    <input type="hidden" asp-for="UserId" />
    <input type="hidden" asp-for="ExternalReference" />

    @if (Model.Result != null && Model.Result.Error != null)
    {
        <div class="field-validation-error">@Model.Result.Error</div>
    }

    <div class="form-button-container">
        <a asp-action="Index" asp-controller="Goal" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <button type="submit" class="btn btn-danger"><i class="bi bi-trash button-icons"></i>Submit</button>
    </div>
</form>

PurpuraWeb/Views/Goal/Details.cshtml
@model GoalViewModel;

@{
    var dueDate = DateTime.MinValue;

    if(Model.DueDate != null)
    {
        var modelDate = (DateTime)Model.DueDate;
        dueDate = modelDate.Date;
    }

    var barPercentageStyle = $"style=width:{Model.PercentageComplete}%";
}

<div class="details-container">
    <h1>@Model.Name</h1>
    <dl>
        <dt>Due Date</dt>
        <dd>@(dueDate != DateTime.MinValue ? dueDate.ToShortDateString() : "N/A")</dd>

        <dt>Description</dt>
        <dd>@Model.Description</dd>

        <dt class="mb-2">Progress @($"{Model.PercentageComplete}%")</dt>
        <dd>
            <div class="progress mb-3 goal-details-progress-bar" role="progressbar">
                <div class="progress-bar" @barPercentageStyle></div>
            </div>
        </dd>
    </dl>
    <div>
        <a asp-action="Edit" asp-controller="Goal" asp-route-reference="@Model.ExternalReference" class="btn btn-purpura"><i class="bi bi-pencil-square button-icons"></i>Edit</a>
    </div>
</div>

PurpuraWeb/Views/Goal/Edit.cshtml
@model GoalViewModel;

<h1 class="form-title">Edit Goal</h1>

<form asp-action="Edit" asp-controller="Goal" asp-route-reference="@Model.ExternalReference" method="post" class="post-forms">

    <div class="form-check form-switch due-date-switch-container">
        <input class="form-check-input form-control" type="checkbox" role="switch" id="due-date-switch" asp-for="IsDateRequired">
        <label class="form-check-label" for="switchCheckDefault">Due Date Required</label>
    </div>

    <div class="form-floating mb-3 due-date-field-container" style="display: none;">
        <input class="form-control" type="date" asp-for="DueDate" placeholder="1" />
        <label asp-for="DueDate">Due Date</label>
        <span asp-validation-for="DueDate"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" type="text" asp-for="Name" placeholder="My Goal" />
        <label asp-for="Name">Goal Name</label>
        <span asp-validation-for="Name" class="mb-3"></span>
    </div>

    <div class="form-floating mb-3">
        <textarea class="form-control" asp-for="Description" placeholder=""></textarea>
        <label asp-for="Description">Description</label>
        <span asp-validation-for="Description"></span>
    </div>

    <div class="form-floating mb-3">
        <input class="form-control" asp-for="PercentageComplete" placeholder="">
        <label asp-for="PercentageComplete">Percentage Complete</label>
        <span asp-validation-for="PercentageComplete"></span>
    </div>

    <input type="hidden" asp-for="UserId" />
    <input type="hidden" asp-for="ExternalReference" />

    @if(Model.Result != null && Model.Result.Error != null)
    {
        <div class="field-validation-error">@Model.Result.Error</div>
    }

    <div class="form-button-container">
        <a asp-action="Index" asp-controller="Goal" class="btn btn-secondary"><i class="bi bi-x button-icons"></i>Cancel</a>
        <button type="submit" class="btn btn-success"><i class="bi bi-pencil-square button-icons"></i>Submit</button>
    </div>
</form>

@section Scripts {
    <script>
        if(@Model.OperationFailure.ToString().ToLower()){
            toastr.error("Edit failed.")
        }

        goalCreateEditForms();
    </script>
}

PurpuraWeb/Views/Goal/Index.cshtml
@using Purpura.Models.Entities
@model GoalIndexViewModel

@if (Model.Goals.Any())
{
    <h1 class="page-heading">Goals</h1>

    <a asp-controller="Goal" asp-action="Create" class="btn btn-purpura mb-3 mt-3" id="create-goal-button-with-goals"><i class="bi bi-plus-lg button-icons"></i>Create New Goal</a>

    <div id="goal-card-container" style="visibility: hidden;">

            @foreach(var goal in Model.Goals)
            {
                var dueDate = DateTime.MinValue;

                if(goal.DueDate != null)
                {
                    var modelDate = (DateTime)goal.DueDate;
                    dueDate = modelDate.Date;
                }

                var barPercentageStyle = $"style=width:{goal.PercentageComplete}%";

                <div class="card goal-cards mb-3 mb-xs-3 m-md-2">
                    <div class="card-header">
                        <i class="bi bi-trophy"></i> @goal.Name
                    </div>
                    <div class="card-body">
                        <p>@goal.Description</p>
                        <p>@(dueDate != DateTime.MinValue ? $"Due Date: {dueDate.ToShortDateString()}" : "")</p>

                        <div class="goal-card-progress-buffer"></div>

                        <div class="goal-card-progress">
                            <p>@($"Complete: {goal.PercentageComplete}%")</p>
                            <div class="progress mb-3" role="progressbar">
                                <div class="progress-bar" @barPercentageStyle></div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer goal-cards-footer">
                        <a class="btn btn-purpura" asp-controller="Goal" asp-action="Details" asp-route-reference="@goal.ExternalReference">Details</a>
                        <a asp-action="Delete" asp-controller="Goal" asp-route-reference="@goal.ExternalReference" class="btn btn-danger">Delete</a>
                    </div>
                </div>

            }
    </div>

    
}
else
{
    <h1 class="page-heading">No goals set yet!</h1>

    <div id="goal-icon-container">
        <i class="bi bi-trophy"></i>
    </div>

    <a asp-controller="Goal" asp-action="Create" class="btn btn-purpura" id="create-goal-button"><i class="bi bi-plus-lg button-icons"></i>Create New Goal</a>
}


@section Scripts{
    <script>
        goalCardContainerListener();
    </script>
}