PurpuraWeb/Controllers/AnnualLeaveController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Purpura.Abstractions.ServiceInterfaces;
using Purpura.Common.Results;
using Purpura.Models.ViewModels;
using Purpura.Utility.Helpers;

namespace PurpuraWeb.Controllers
{
    public class AnnualLeaveController : Controller
    {
        private readonly IAnnualLeaveService _annualLeaveService;
        private readonly UserManager<IdentityUser> _userManager;

        public AnnualLeaveController(IAnnualLeaveService annualLeaveService,
            UserManager<IdentityUser> userManager)
        {
            _annualLeaveService = annualLeaveService;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> _IndexDayCount()
        {
            var currentUserId = _userManager.GetUserId(User);
            var currentUserAnnualLeave = await _annualLeaveService.GetUserAnnualLeaveCountAsync(currentUserId);

            var viewModel = new AnnualLeaveIndexViewModel
            {
                AnnualLeaveDaysRemaining = currentUserAnnualLeave,
                AnnualLeaveDaysUsed = 28 - currentUserAnnualLeave
            };

            return PartialView(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> _Create()
        {
            var viewModel = new AnnualLeaveViewModel
            {
                LeaveTypeSelectList = EnumHelpers.GenerateLeaveTypeSelectList(),
                UserId = _userManager.GetUserId(User)
            };

            var overlapPreCheck = await _annualLeaveService.CheckForLeaveOverlapsAsync(viewModel.UserId, viewModel.StartDate, viewModel.EndDate, null);
            viewModel.HasOverlap = overlapPreCheck.HasOverlap;

            return PartialView("_BookTimeOffForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<Result> _Create(AnnualLeaveViewModel bookedOffPeriod)
        {
            if (ModelState.IsValid)
            {
                if (bookedOffPeriod.HasOverlap)
                    return Result.Failure("Overlapping leave periods can not be submitted.");

                return await _annualLeaveService.CreateAsync(bookedOffPeriod);
            }

            return Result.Failure("Fields are missing.");
        }

        [HttpGet]
        public async Task<IActionResult> _BookedLeaveTable()
        {
            var viewModel = new AnnualLeaveIndexViewModel 
            { 
                BookedLeave = await _annualLeaveService.GetBookedLeaveByUserIdAsync(_userManager.GetUserId(User)) 
            };

            return PartialView(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> _Edit(string externalReference)
        {
            AnnualLeaveViewModel? viewModel = null;
            viewModel = await _annualLeaveService.GetByExternalReferenceAsync(externalReference);

            if(viewModel == null)
            {
                viewModel = new();
                viewModel.Result = Result.Failure("Can not find entity");
            }
            else
            {
                viewModel.LeaveTypeSelectList = EnumHelpers.GenerateLeaveTypeSelectList();

                var overlapPreCheck = await _annualLeaveService.CheckForLeaveOverlapsAsync(viewModel.UserId, viewModel.StartDate, viewModel.EndDate, viewModel.ExternalReference);
                viewModel.HasOverlap = overlapPreCheck.HasOverlap;
            }

            return PartialView("_BookTimeOffForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<Result> _Edit(AnnualLeaveViewModel bookedOffPeriod)
        {
            if (ModelState.IsValid)
            {
                if (bookedOffPeriod.HasOverlap)
                    return Result.Failure("Overlapping leave periods can not be submitted.");

                return await _annualLeaveService.EditAsync(bookedOffPeriod);
            }

            return Result.Failure("Fields are missing.");
        }

        [HttpGet]
        public async Task<IActionResult> _Delete(string externalReference)
        {
            AnnualLeaveViewModel? viewModel = null;

            viewModel = await _annualLeaveService.GetByExternalReferenceAsync(externalReference);

            if(viewModel == null)
            {
                viewModel = new();
                viewModel.Result = Result.Failure("Can not find entity");
            }
            else
            {
                viewModel.LeaveTypeSelectList = EnumHelpers.GenerateLeaveTypeSelectList();
                viewModel.UserId = _userManager.GetUserId(User);
            }

            return PartialView("_BookTimeOffForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<Result> _Delete(AnnualLeaveViewModel bookedOffPeriod)
        {
            ModelState.Remove("HasOverlap");

            if (ModelState.IsValid)
            {
                return await _annualLeaveService.DeleteAsync(bookedOffPeriod);
            }

            return Result.Failure("Delete failed.");
        }

        [HttpPost]
        public async Task<OverlapResult> CheckForLeaveOverlaps(string userId, DateTime startDate, DateTime endDate, string? leaveExtRef)
        {
            return await _annualLeaveService.CheckForLeaveOverlapsAsync(userId, startDate, endDate, leaveExtRef);
        }
    }
}

PurpuraWeb/Views/AnnualLeave/Index.cshtml
<h1>Annual Leave</h1>

<div class="spinner-container">
</div>

<div id="day-count-container" data-get-day-count="@Url.Action("_IndexDayCount", "AnnualLeave")">
</div>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#annual-leave-form-modal" data-crud-method="create">
    Book Time Off
</button>

<div id="booked-leave-table-container" data-get-booked-leave-container="@Url.Action("_BookedLeaveTable", "AnnualLeave")">
</div>

<div class="modal fade" id="annual-leave-form-modal" data-get-modal-content="@Url.Action("_Create", "AnnualLeave")" data-get-edit-modal-content="@Url.Action("_Edit", "AnnualLeave")" data-get-delete-modal-content="@Url.Action("_Delete", "AnnualLeave")" data-check-overlap-url="@Url.Action("CheckForLeaveOverlaps", "AnnualLeave")" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="save-changes-button" type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

PurpuraWeb/Views/AnnualLeave/_BookTimeOffForm.cshtml
@model AnnualLeaveViewModel;

@if(Model.Result == null)
{
    
    <form id="leave-form" method="post" data-crud-method="" data-create-url="@Url.Action("_Create", "AnnualLeave")" data-edit-url="@Url.Action("_Edit", "AnnualLeave")" data-delete-url="@Url.Action("_Delete", "AnnualLeave")" data-check-overlap-url="@Url.Action("CheckForLeaveOverlaps", "AnnualLeave")">
        <div class="modal-body">
        
            <div class="form-floating mb-3">
                <input class="form-control" type="date" name="StartDate" asp-for="StartDate" id="start-date"/>
                <label asp-for="StartDate">Start Date</label>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>

            <div class="form-floating mb-3">
                <input class="form-control" type="date" name="EndDate"  asp-for="EndDate" id="end-date"/>
                <label asp-for="EndDate">End Date</label>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>

            <div id="overlap-warning"></div>

            <div class="form-floating mb-3">
                <select class="form-select" asp-for="Type" asp-items="@Model.LeaveTypeSelectList" name="Type"></select>
                <label asp-for="Type">Leave Type</label>
            </div>

            <div class="form-floating mb-3">
                <textarea class="form-control" name="Details" asp-for="Details">@Model.Details</textarea>
                <label asp-for="Details">Details</label>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>

            <div id="delete-warning"></div>

            <input type="hidden" value="@Model.UserId" name="UserId" id="user-id"/>
            <input type="hidden" value="@Model.HasOverlap.ToString().ToLower()" name="HasOverlap" id="has-overlap" />
            <input type="hidden" value="@Model.ExternalReference" name="ExternalReference" id="ext-ref" />
        </div>
    
    </form>
}
else
{
    <h2 class="result-failure-error">@Model.Result.Error</h2>
}

PurpuraWeb/Views/AnnualLeave/_BookedLeaveTable.cshtml
@using Purpura.Utility.Helpers

@model AnnualLeaveIndexViewModel;

@if (Model.BookedLeave.Any())
{
    <div style="overflow-x: auto;">
        <table class="table booked-leave-table">
            <thead>
                <tr>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Leave Type</th>
                    <th>Details</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var leave in Model.BookedLeave)
                {
                    <tr>
                        <td>@leave.StartDate.ToShortDateString()</td>
                        <td>@leave.EndDate.ToShortDateString()</td>
                        <td>@EnumHelpers.GetEnumDescription(leave.Type)</td>
                        <td>@(leave.Details != null && leave.Details.Length > 30 ? leave.Details.Substring(0, 30) + "..." : leave.Details)</td>
                        <td>
                            <a class="edit-buttons" data-crud-method="edit" data-external-reference="@leave.ExternalReference" data-bs-toggle="modal" data-bs-target="#annual-leave-form-modal">
                                <i class="bi bi-pencil-square" style="color: darkkhaki;"></i>
                            </a>
                        </td>
                        <td>
                            <a class="delete-buttons" data-external-reference="@leave.ExternalReference" data-crud-method="delete" data-bs-toggle="modal" data-bs-target="#annual-leave-form-modal">
                                <i class="bi bi-trash-fill" style="color: darkred;"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

PurpuraWeb/Views/AnnualLeave/_IndexDayCount.cshtml
@model AnnualLeaveIndexViewModel;

<p>You currently have @(Model.AnnualLeaveDaysRemaining > 0 ? $"{Model.AnnualLeaveDaysRemaining} days left of annual leave!" : "no annual leave to take.")</p>
<p>You have used @Model.AnnualLeaveDaysUsed days.</p>